{{- if .Values.createCRDs }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dnsentries.dns.gardener.cloud
  labels:
    helm.sh/chart: {{ include "external-dns-management.chart" . }}
    app.kubernetes.io/name: {{ include "external-dns-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.dnsName
    description: DNS ObjectName
    name: DNS
    type: string
  - JSONPath: .status.providerType
    description: Provider type
    name: TYPE
    type: string
  - JSONPath: .status.provider
    description: Provider
    name: PROVIDER
    type: string
  - JSONPath: .status.state
    description: Status of DNS entry in cloud provider
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: dns.gardener.cloud
  names:
    kind: DNSEntry
    listKind: DNSEntryList
    plural: dnsentries
    shortNames:
    - dnse
    singular: dnsentry
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dnsannotations.dns.gardener.cloud
  labels:
    helm.sh/chart: {{ include "external-dns-management.chart" . }}
    app.kubernetes.io/name: {{ include "external-dns-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.resourceRef.apiVersion
      description: API Version of the annotated object
      name: RefAPI
      type: string
    - JSONPath: .spec.resourceRef.kind
      description: Kind of the annotated object
      name: RefKind
      type: string
    - JSONPath: .spec.resourceRef.name
      description: Name of the annotated object
      name: RefName
      type: string
    - JSONPath: .spec.resourceRef.namespace
      description: Namspace of the annotated object
      name: RefNamespace
      type: string
    - JSONPath: .status.active
      description: Indicates that annotation is observed by a DNS sorce controller
      name: Active
      type: boolean
    - JSONPath: .metadata.creationTimestamp
      name: AGE
      type: date
  group: dns.gardener.cloud
  names:
    kind: DNSEntry
    listKind: DNSEntryList
    plural: dnsentries
    shortNames:
      - dnse
    singular: dnsentry
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dnsowners.dns.gardener.cloud
  labels:
    helm.sh/chart: {{ include "external-dns-management.chart" . }}
    app.kubernetes.io/name: {{ include "external-dns-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.ownerId
    description: Owner Id
    name: OWNERID
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: dns.gardener.cloud
  names:
    kind: DNSOwner
    listKind: DNSOwnerList
    plural: dnsowners
    shortNames:
    - dnso
    singular: dnsowner
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dnsproviders.dns.gardener.cloud
  labels:
    helm.sh/chart: {{ include "external-dns-management.chart" . }}
    app.kubernetes.io/name: {{ include "external-dns-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.type
    description: Provider type
    name: TYPE
    type: string
  - JSONPath: .status.state
    description: Status of DNS provider
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: dns.gardener.cloud
  names:
    kind: DNSProvider
    listKind: DNSProviderList
    plural: dnsproviders
    shortNames:
    - dnspr
    singular: dnsprovider
  subresources:
    status: {}
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
{{- end }}
